### ISSUE TITLE
Should this repo be private?

### ISSUE THREAD

**Issue by mstojcevich** [frc-862/valkyrie#31]
Since it's build season, perhaps this repo should be made private unless there's some FRC rule I'm not aware of

**Comment by phurley** [comment]
I am flexible on the issue. I don't think anyone (certainly not many) people really care enough. I hope we do really well this year, and everyone wants to see our code, but for now I think public is easier, and fine. 

Anyone disagree?

**Comment by mstojcevich** [comment]
Sounds good, I just wasn't sure as IIRC the past few repos have been private. I'm all for sharing.
