### ISSUE TITLE
Automatic Shifting

### ISSUE THREAD

**Issue by LukeFenstermacher** [frc-862/valkyrie#4]
Automatic shifting from high gear to low gear during heavy deceleration and from low gear to high gear during heavy acceleration.

**Comment by LukeFenstermacher** [comment]
Class to perform checks to see if any indications of possible drivetrain failure occur.

**Comment by LukeFenstermacher** [comment]
Automatic downshift of drivetrain when the class checking for failure returns true.

**Comment by phurley** [comment]
I am closing this as I created a more detailed set of issues that break it out into parts. Thanks.
