### ISSUE TITLE
Complete initial dashboard layout

### ISSUE THREAD

**Issue by phurley** [frc-862/valkyrie#41]

**Comment by phurley** [comment]
The default Java dashboards do not seem to work very well, so we need to investigate either using the LabVIEW interface or one of the other team based systems.

**Comment by darren862** [comment]
Do the Cheesy Poofs have anything good that we can take?

**Comment by phurley** [comment]
See https://github.com/Team254/FRC-2016-Public/tree/master/dash for a link to what the poofs did last year. There is also https://github.com/erikuhlmann/SmartDashboard.js which looks to be in slightly wider use.

**Comment by phurley** [comment]
Darren and Collin found this one too 

https://frcdashboard.github.io/
